# Generated by Django 4.1.3 on 2022-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_user'),
        ('app', '0006_alter_order_status'),
    ]

    operations = [
    ]
