# Generated by Django 4.1.3 on 2022-12-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_date_order_order_date_order_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ordered', 'ordered'), ('approved', 'approved'), ('picked_up', 'picked_up')], default='Принят', max_length=20),
        ),
    ]
