# Generated by Django 4.1.3 on 2022-12-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_approval_date_alter_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ordered', 'ordered'), ('approved', 'approved'), ('picked_up', 'picked_up')], default='ordered', max_length=20),
        ),
    ]
